home/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.HomePage, name='home-page'),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import handler404, handler500

urlpatterns = [
    path('', include('home.urls'), name='home-urls'),
    path('admin/', admin.site.urls),
    path('portfolio/', include('portfolio.urls'), name='portfolio_urls'),
    path('accounts/', include('allauth.urls')),
]
handler404 = 'main.views.handler404'
handler500 = 'main.views.handler500'

portfolio/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.get_portfolio_list, name='get_portfolio_list'),
    path('edit/<portfolio_id>', views.edit_portfolio, name='edit_portfolio'),
    path(
        'delete/<portfolio_id>', views.delete_portfolio,
        name='delete_portfolio'),
    path('create', views.create_portfolio, name='create_portfolio_url'),
    path('view/<portfolio_id>', views.get_asset_list, name='get_asset_list'),
    path('get/<portfolio_id>', views.get_asset, name='get_asset'),
    path(
        'add/<int:portfolio>/<coin>/<price>', views.add_asset,
        name='add_asset_form'),
    path(
        'update/<int:pk>/<str:b_or_s>/<coin>/<price>',
        views.update_asset, name='update_asset'),
]

portfolio/models.py
from django.db import models
from django.contrib.auth.models import User


class Portfolio(models.Model):
    """
    Class that defines the Portfolio Model
    """
    name = models.CharField(max_length=9, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name


class Asset(models.Model):
    """
    Class that defines the Asset Model
    """
    portfolio_name = models.ForeignKey(Portfolio, on_delete=models.CASCADE)
    ticker = models.CharField(max_length=6)
    quantity = models.DecimalField(max_digits=10, decimal_places=3)
    price = models.DecimalField(max_digits=10, decimal_places=3)
    average_price = models.JSONField(blank=True, null=True)
    usd_spent = models.DecimalField(max_digits=10, decimal_places=3)
    usd_earned = models.DecimalField(max_digits=10, decimal_places=3)
    added_to_portfolio = models.DateTimeField(auto_now_add=True)
    pnl = models.DecimalField(max_digits=10, decimal_places=3, default='0.00')

    class Meta:
        ordering = ['-ticker']

    def __repr__(self):
        return self.ticker

portfolio/forms.py
from django import forms
from .models import Portfolio, Asset


class PortfolioForm(forms.ModelForm):
    """
    Form that allows user to create a portflio
    """
    class Meta:
        model = Portfolio
        fields = ['name']


class AddAsset(forms.ModelForm):
    """
    Form that allows user to add a new asset to a portfolio
    """
    class Meta:
        model = Asset
        fields = ['quantity']


class UpdateAsset(forms.ModelForm):
    """
    Form that allows the user to update the quantity of their asset
    """
    class Meta:
        model = Asset
        fields = ['quantity']

portfolio/views.py
import json
from django.shortcuts import render, redirect, get_object_or_404, reverse
from django.contrib.auth.models import User
from django.conf import settings
from django.contrib import messages
from requests import Request, Session
from requests.exceptions import ConnectionError, Timeout, TooManyRedirects
from .models import Portfolio, Asset
from .forms import PortfolioForm, AddAsset, UpdateAsset

tickerList = []
global coins
URL = 'https://pro-api.coinmarketcap.com/v1/cryptocurrency/listings/latest'

params = {
    'start': '1',
    'limit': '2000',
    'convert': 'USD'
}

headers = {
    'X-CMC_PRO_API_KEY': settings.APIKEY,
    'Accepts': 'application/json'
}

session = Session()
session.headers.update(headers)


def call_api():
    """
    Function which will call the API with appropriate params
    """
    try:
        response = session.get(URL, params=params)
        data = json.loads(response.text)
        coins = data['data']
        get_ticker_list(data)

        return coins

    except (ConnectionError, Timeout, TooManyRedirects) as e:
        print(e)


def get_ticker_list(data):
    """
    Function which generates a list of valid tickers
    """
    for d in data['data']:
        ticker_from_api = d['symbol']
        if ticker_from_api not in tickerList:
            tickerList.append(ticker_from_api)


def get_coin_price(ticker, coins):
    """
    Will get the price of a coin
    """
    if ticker in tickerList:
        for x in coins:
            if x['symbol'] == ticker:
                price = float((x['quote']['USD']['price']))
        return price


def validate_ticker(ticker):
    """
    Will validate if the users ticker exits in tickerList
    """
    for x in tickerList:
        if ticker in tickerList:
            return True

        else:
            return False


def get_portfolio_list(request):
    """
    View to get all user portfolios
    """
    portfolios = Portfolio.objects.filter(user=request.user)
    portfolio_balance_list = []
    total_portfolio_balance = 0
    returnedCoin = call_api()

    for i in portfolios:
        total = 0
        portfolio_id = i.id

        assets = Asset.objects.filter(portfolio_name=portfolio_id)
        quantity = assets.values_list('quantity', flat=True)

        portfolio_assets = assets.values_list('ticker', flat=True)
        asset_prices = []
        for i in portfolio_assets:
            current_asset_price = get_coin_price(i, returnedCoin)
            rounded_price = round(current_asset_price, 3)
            asset_prices.append(rounded_price)

        current_holdings = []
        for index, value in enumerate(quantity):
            new_holdings = float(quantity[index]) * asset_prices[index]
            rounded_holdings = round(new_holdings, 3)
            current_holdings.append(rounded_holdings)

        for i in current_holdings:
            total = total + i

        rounded_total = round(total, 3)
        portfolio_balance_list.append(rounded_total)

    for i in portfolio_balance_list:
        total_portfolio_balance = total_portfolio_balance + i

    zipped_assets = zip(portfolios, portfolio_balance_list)
    zipped_context = tuple(zipped_assets)

    context = {
        'portfolios': zipped_context,
        'TPB': total_portfolio_balance
    }
    return render(request, 'portfolio/portfolio.html', context)


def create_portfolio(request):
    """
    View that allows users to create a portfolio
    """
    form = PortfolioForm(request.POST or None)

    if form.is_valid():
        obj = form.save(commit=False)
        obj.user = request.user
        obj.slug = form['name'].value()
        obj.usd_value = 0.00
        obj.save()
        return redirect('get_portfolio_list')

    context = {'form': form}
    return render(request, 'portfolio/create_portfolio.html', context)


def edit_portfolio(request, portfolio_id):
    """
    View that allows the user to edit a portfolio's name
    """
    portfolio = get_object_or_404(Portfolio, id=portfolio_id)
    if request.method == 'POST':
        form = PortfolioForm(request.POST, instance=portfolio)
        if form.is_valid():
            form.save()
            return redirect('get_portfolio_list')
    form = PortfolioForm(instance=portfolio)
    context = {
        'form': form
    }
    return render(request, 'portfolio/edit_portfolio.html', context)


def delete_portfolio(request, portfolio_id):
    """
    View that allows a user to delete a portfolio
    """
    portfolio = get_object_or_404(Portfolio, id=portfolio_id)
    portfolio.delete()
    return redirect('get_portfolio_list')


def get_asset_list(request, portfolio_id):
    """
    View that retrieves all assets within a single portfolio and displays them
    """
    average_prices = []
    pnl = []
    returnedCoin = call_api()
    assets = Asset.objects.filter(portfolio_name=portfolio_id)

    portfolio_assets = assets.values_list('ticker', flat=True)
    portfolio_average_price = assets.values_list('average_price', flat=True)

    asset_prices = []
    for i in portfolio_assets:
        current_asset_price = get_coin_price(i, returnedCoin)
        rounded_price = round(current_asset_price, 3)
        asset_prices.append(rounded_price)

    quantity = assets.values_list('quantity', flat=True)

    current_holdings = []
    for index, value in enumerate(quantity):
        new_holdings = float(quantity[index]) * asset_prices[index]
        rounded_holdings = round(new_holdings, 3)
        current_holdings.append(rounded_holdings)

    for index, value in enumerate(portfolio_average_price):
        asset_average_price = portfolio_average_price[index]
        list_of_average_price_per_asset = list(asset_average_price.values())

        total = 0
        for index, value in enumerate(list_of_average_price_per_asset):
            total = total + list_of_average_price_per_asset[index]
            average = round(total / len(list_of_average_price_per_asset), 3)

        average_prices.append(average)

    for index, value in enumerate(average_prices):
        averge_price_holdings = average_prices[index] * float(quantity[index])
        profit = round(current_holdings[index] - averge_price_holdings, 3)
        pnl.append(profit)

    zipped_assets = zip(assets, asset_prices, current_holdings,
                        average_prices, pnl)
    zipped_context = tuple(zipped_assets)

    context = {
        'assets': zipped_context,
        'portfolio_id': portfolio_id,
    }
    return render(request, 'portfolio/assets.html', context)


def get_asset(request, portfolio_id):
    """
    View that gets the ticker and ticker price of a coin to ADD
    """
    portfolio = Portfolio.objects.get(pk=portfolio_id)
    returnedCoin = call_api()

    if request.method == "POST":
        coin = request.POST.get("ticker").upper()
        valid = validate_ticker(coin)

        if valid:
            price = get_coin_price(coin, returnedCoin)
            return redirect(add_asset, portfolio.id, coin, price)

        else:
            messages.success(request, f"{coin} does not exist!")

    context = {
        'tickerList': tickerList,
        'portfolio': portfolio,
    }
    return render(request, 'portfolio/get_ticker.html', context)


def add_asset(request, portfolio, coin, price):
    """
    View that allows a user to add a new coin to their portfolio
    """
    portfolio = Portfolio.objects.get(pk=portfolio)
    form = AddAsset()
    if request.method == "POST":
        form = AddAsset(request.POST)
        if form.is_valid():
            try:
                asset = Asset.objects.get(
                    portfolio_name=portfolio, ticker=coin)
                pk = asset.id
                b_or_s = 'buy'
                update_asset(request, pk, b_or_s, coin, price)
                return redirect(reverse('get_asset_list', args=[portfolio.id]))

            except Asset.DoesNotExist:
                obj = form.save(commit=False)
                obj.portfolio_name = portfolio
                obj.price = price
                quantity = float(form['quantity'].value())
                obj.average_price = {
                    'price1': float(request.POST.get('price'))}
                USDspent = float(quantity) * float(price)
                obj.usd_spent = USDspent
                obj.ticker = coin
                obj.pnl = 0.00
                obj.usd_earned = 0.00
                obj.save()
                return redirect(reverse('get_asset_list', args=[portfolio.id]))

    context = {
        'form': form,
        'tickerList': tickerList,
        'ticker': coin,
        'price': price,
    }
    return render(request, 'portfolio/add_asset.html', context)


def update_asset(request, pk, b_or_s, coin, price):
    """
    View that allows a user to Buy or Sell an existing coin
    """
    asset = get_object_or_404(Asset, pk=pk)
    returnedCoin = call_api()
    if request.method == 'POST':
        if coin is not None:
            coin = coin
        else:
            coin = request.POST.get("ticker")
        if price is not None:
            price = get_coin_price(coin, returnedCoin)
        else:
            price = price

        form = UpdateAsset(request.POST, instance=asset)
        asset_qty = float(asset.quantity)
        curr_spent = float(asset.usd_spent)
        curr_usd_earned = float(asset.usd_earned)
        curr_PnL = float(asset.pnl)
        AP = asset.average_price
        print("AveragePrice", AP)
        if b_or_s == 'buy':
            new_qty = float(form['quantity'].value())
            new_inv = float(price) * float(new_qty)
            asset.quantity = asset_qty + new_qty
            asset.usd_spent = curr_spent + new_inv
            AP[f"price{len(AP)+1}"] = float(request.POST.get('price'))
            asset.price = price
            asset.ticker = coin
            asset.save()
            messages.success(
                request, f"{new_qty} {coin} successfully purchased!")

        elif b_or_s == 'sell':

portfolio/templates/portfolio/add_asset.html
{% extends "home/base.html" %}
{% block content %}

<div class="container login-div-container">

    <h1 class="sign-in-text">Add A Coin </h1>  

    <form method='POST'>
        {% csrf_token %}
        <label class="form-label">Coin: {{ ticker }}</label>
        <input type="hidden" name="ticker" id="ticker"><br>
        <label for="price" class="form-label">Coin Price:</label>
        <input type="number" step="any" name="price" id="price" value="{{ price }}"><br>
        {{ form.as_p }}        
        <p> 
            <button class="btn login-btn add-coin-btn" type="submit">Add Coin</button>
        </p>
    </form>
</div>
{% endblock %}

portfolio/templates/portfolio/assets.html
{% extends "home/base.html" %}

{% block content %}

<section class="portfolio-section">
    <section class="heading-section">
        <h1 class="assets-h1">Your Assets</h1>
    </section>
    
    <table class="portfolio-table">
        <tr class="table-header assets-header">
            <th>Name</th>
            <th class="d-none d-sm-table-cell">Price</th>
            <th>Holdings</th>
            <th class="d-none d-sm-none d-md-none d-lg-table-cell">Avg. Buy Price</th>
            <th class="d-none d-sm-none d-md-table-cell">Profit/Loss</th>
            <th>Actions</th> 
        </tr>
        {% for asset,price,holdings,average,pnl in assets %}
            <tr class="asset-table-row portfolio-rows">
                <td>{{ asset.ticker }}</td>   
                <td class="d-none d-sm-table-cell">${{ price }}</td>
                <td>${{ holdings }} 
                    <hr class="table-hr">
                    <span class="qty_data">{{ asset.quantity }}<span class="qty-ticker">{{ asset.ticker }}</span></span>
                </td>   
                <td class="d-none d-sm-none d-md-none d-lg-table-cell">${{ average }}</td>   
                <td class="d-none d-sm-none d-md-table-cell">${{ pnl }}</td>
                
                <!-- Modal Trigger -->
                <td>
                    <button class="btn" data-bs-toggle="modal" data-bs-target="#modal-{{ asset.id }}">
                        <i class="action-icon fa-solid fa-ellipsis-vertical"></i>
                    </button>
                    <!-- Modal -->
                    <div class="modal fade" id="modal-{{ asset.id }}" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="modal-title-{{ asset.id }}" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="modal-title-{{ asset.id }}">Manage Asset</h5>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                </div>
                                <div class="modal-body">
                                    <table class="portfolio-table modal-table">
                                        <tr class="table-header">
                                            <th>Name</th>
                                            <th>Holdings</th>
                                            <th>Actions</th>
                                        </tr>
                                            <tr class="portfolio-rows">
                                                <td>{{ asset.ticker }}</td>
                                                <td>{{ asset.quantity }}</td>
                                                <td>
                                                    <section class="modal-btn-section">
                                                        <section class="modal-btns">
                                                            <a class="btn btn-purple modal-btn" href="{% url 'update_asset' asset.id 'buy' asset.ticker None %}">
                                                                Buy
                                                            </a>
                                                        </section>
                                                    </section>

                                                    <section class="modal-btn-section">
                                                        <section class="modal-btns">
                                                            <a class="btn btn-green modal-btn sell-btn" href="{% url 'update_asset' asset.id 'sell' asset.ticker None %}">
                                                                Sell
                                                            </a>
                                                        </section>
                                                    </section>
                                                </td>
                                            </tr>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </td>
            </tr>
            
        {% empty %}
            <tr class="asset-table-row">
                <td colspan="6">No Assets Found on this Portfolio</td>
                <tr>
        {% endfor %}
    </table>

    <section class="add-new-container">
        <section class="add-new-section">
            <a class="add-new-a" href="{% url 'get_asset' portfolio_id %}">
                <i class="fa-solid fa-circle-plus"></i> Add New
            </a>
        </section>
    </section>
    
</section>

{% endblock %}

portfolio/templates/portfolio/buy_sell_asset.html
{% extends "home/base.html" %}

{% block content %}

<div class="container login-div-container">
    <h1 class="sign-in-text">{{ b_or_s|title }} {{ asset.ticker }} </h1>  
    
    <form method='POST'>
        {% csrf_token %}
        <input type="hidden" name="ticker" id="ticker" value="{{ asset.ticker }}">
        {{ form.as_p }}
        <label for="id_price">Price:</label>
        <input type="number" name="price" step="any" id="id_price" class="my-2" value="{{ price }}" required>
        <div>
            <p> 
                <button class="btn login-btn b_s-btn" type="submit">Add Transaction</button>
            </p>
        </div>
    </form>

</div>


{% endblock %}

portfolio/templates/portfolio/create_portfolio.html
{% extends "home/base.html" %}

{% block content %}


<div class="container login-div-container">
    <h1 class="sign-in-text">Create a Portfolio</h1>  
    
    <form method='POST' action="{%url 'create_portfolio_url' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <div>
            <p> 
                <button class="btn login-btn right create-portfolio-btn" type="submit">Create Portfolio</button>
            </p>
        </div>
    </form>
</div>

{% endblock %}

portfolio/templates/portfolio/edit_portfolio.html
{% extends "home/base.html" %}

{% block content %}

<div class="container login-div-container">
    <h1 class="sign-in-text">Edit Portfolio</h1>  

<form method='POST' >
    {% csrf_token %}
    {{ form.as_p }}
    <div>
        <p> 
            <button class="btn login-btn right edit-portfolio-btn" type="submit">Update Portfolio</button>
        </p>
    </div>
</form>

{% endblock %}

portfolio/templates/portfolio/get_ticker.html
{% extends "home/base.html" %}

{% block content %}

<div class="container login-div-container">
    <h1 class="sign-in-text">Chose a Coin </h1>
    
    <form method='POST' action="{% url 'get_asset' portfolio.id %}">
        {% csrf_token %}
        <label for="ticker" class="form-label">Select a Coin:</label>
        <input name="ticker" id="ticker" class="form-control" list="tickers" placeholder="Type to search...">
        <datalist id="tickers">
        {% for ticker in tickerList %}
            <option value="{{ ticker }}">{{ ticker }}</option>
        {% endfor %}
        </datalist>
        <!-- {{ form.as_p }} -->
        <div>
            <!-- <p>  -->
                <button class="btn login-btn add-coin-btn" type="submit">Next</button>
            <!-- </p> -->
        </div>
    </form>
</div>

{% endblock %}

portfolio/templates/portfolio/portfolio.html
{% extends "home/base.html" %}

{% block content %}

<section class="portfolio-section">
    <section class="portfolio-title-section">
        <h1 class="portfolio-details portfolio-h1">Your Portfolios</h1> 
        <h3 class="portfolio-details portfolio-details-2">Total Value:</h3> 
        <h4 class="total-portfolio-bal"> = ${{ TPB }}</h4> 
    </section>
    
    <table class="portfolio-table">
        <tr class="table-header portfolio-header">
            <th>Name</th>
            <th>Value</th>
            <th></th>
        </tr>

        {% for portfolio, value in portfolios %}
            <tr class="portfolio-rows">
                <td>{{ portfolio.name }}</td>   
                <td>${{ value }}</td>   
    
                <td>
                    <section class="view-btn-section">
                        <section class="view-btn">
                            <a class="view-btn-a" href="{% url 'get_asset_list' portfolio.id %}">
                                View Assets
                            </a>
                        </section>
                    </section>
                </td>
            </tr>
            {% empty %}
            <tr>
                <td>Create A Portfolio</td>
                <td colspan="2">0.00</td>
            </tr>
        {% endfor %}
    </table>

    <section>
        <section class="create-portfolio-section">
            <a class="create-portfolio-a" href="{% url 'create_portfolio_url' %}">
                <i class="fa-solid fa-circle-plus"></i> Create A Portfolio
            </a>
        </section>

        <!-- modal trigger -->
        <section class="manage-portfolio-section">
            <button class="btn manage-btn" data-bs-toggle="modal" data-bs-target="#icon-modal">
                <i class="fa-solid fa-ellipsis-vertical"></i>Manage Portfolios
            </button> 
        </section>
    </section>
</section>

    <!-- Modal -->
    <div class="modal fade" id="icon-modal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="modal-title" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="modal-title">Manage Portfolios</h5>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <table class="portfolio-table modal-table">
                    <tr class="table-header">
                        <th>Name</th>
                        <th>Value</th>
                        <th>Actions</th>
                    </tr>
            
                    {% for portfolio,value in portfolios %}
                    
                        <tr class="portfolio-rows">
                            <td>{{ portfolio.name }}</td>   
                            <td>${{ value }}</td>   
                            <td>
                                <section class="modal-btn-section">
                                    <section class="modal-btns">
                                        <a class="btn btn-purple modal-btn" href="{% url 'edit_portfolio' portfolio.id %}">
                                            Edit
                                        </a>
                                    </section>
                                </section>

                                <section class="modal-btn-section">
                                    <section class="modal-btns">
                                        <a class="btn btn-green modal-btn del-btn" href="{% url 'delete_portfolio' portfolio.id %}">
                                            Delete
                                        </a>
                                    </section>
                                </section>
                            </td>
                        </tr>

                    {% endfor %}
                </table>       
            </div>
          </div>
        </div>
      </div>

{% endblock %}